# Generated by Django 4.0.6 on 2022-07-21 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='domain',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
