# Generated by Django 4.0.6 on 2022-07-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
